### ISSUE TITLE
lein-voom broken since leinigen >= 2.8.0

### ISSUE THREAD

**Issue by marco-m** [LonoCloud/lein-voom#60]
Leinigen 2.8.0 released 2017-10-18
Latest working version is Leinigen 2.7.1 released 2016-09-22

Using `:plugins [[lein-voom "0.1.0-20170920_222746-ga58a315"]]` in my `project.clj`:

This works:
```
$ lein upgrade 2.7.1
...
Leiningen 2.7.1 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM
$ lein voom build-deps
-- build-deps for mikado-graph
```

This breaks:
```
$ lein upgrade 2.8.0
Leiningen 2.8.0 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM
$ lein voom build-deps | head -5
clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: org.sonatype.aether.util.version.GenericVersionScheme, compiling:(leiningen/voom.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7391)
    clojure.lang.RT.loadResourceScript (RT.java:372)
    clojure.lang.RT.loadResourceScript (RT.java:363)
    clojure.lang.RT.load (RT.java:453)
...
```

**Comment by abrooks** [comment]
Exciting!

Thanks for the bug report. I'm fixing a couple of other issues and hope to get to this over the Christmas break. Pull requests welcome! :)

**Comment by abrooks** [comment]
Turns out this was a lot easier to fix than I expected. I'm on a roll today.

Fix pushed in 8076aed3f83. Also pushed new artifact: `[lein-voom "0.1.0-20171223_194437-g8076aed"]`.

Reopen if you see any issues.

**Comment by marco-m** [comment]
Hello Aaron, thanks for the very quick reaction! Unfortunately I still see a bug as follows:

```
$ lein --version
Leiningen 2.8.1 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM

$ lein new app foo
Generating a project called foo based on the 'app' template.
$ cd foo/
```
Add lines
```
  :dependencies [[org.clojure/clojure "1.8.0"]
                 ^{:voom {:repo "https://github.com/ring-clojure/ring" :branch "1.3"}}
                [ring/ring-core "1.3.0-RC1-20140519_142204-gaf0379b"]]
  :plugins [[lein-voom "0.1.0-20171223_194437-g8076aed"]]
```
to `project.clj`. Then:
```
$ lein deps
$ lein voom freshen
Fetching: https://github.com/ring-clojure/ring (aHR0cHM6Ly9naXRodWIuY29tL3JpbmctY2xvanVyZS9yaW5n)
Fetching: https://github.com/aysylu/loom (aHR0cHM6Ly9naXRodWIuY29tL2F5c3lsdS9sb29t)
Indexing https://github.com/ring-clojure/ring commits 999/999 ...done
org.clojure/clojure                      1.8.0
ring/ring-core                           1.2.3 -> 1.3.0-RC1-20140519_142204-gaf0379b
org.clojure/tools.nrepl                  0.2.12
clojure-complete/clojure-complete        0.2.4
```
And now:
```
$ lein voom build-deps
-- build-deps for foo
Failed to resolve dependency: Could not resolve dependencies
{:exception-data {:suppress-msg true, :exit-code 1}}
```

Exactly same error with lein 2.8.0.

**Comment by abrooks** [comment]
Hm. I fixed one issue but didn't see the other. Sorry about that.

This is what we get for having virtually no test suite. (I'm working on that, actuallly.) I'm reopening the issue.

**Comment by abrooks** [comment]
@marco-m I've added a test that now fails in the mode you show. I don't expect to have much time the next several days to look at this but should be able to get to it next week.

Thanks again for the bug report!

**Comment by marco-m** [comment]
@abrooks thank you! :-) I wanted to ask if you were interested in a Docker-based test system (since voom changes global state like $HOME/.m2) but I noticed that you already have it, very good!

**Comment by abrooks** [comment]
@marco-m Merry Christmas! I believe this last version (`[lein-voom "0.1.0-20171225_233657-g7962d1d"]`) should fix your issues. Please let me know if you see anything else!

**Comment by marco-m** [comment]
@abrooks thanks again, and happy new year! :-) I still have some failures, I will try to add more  tests to the regression tests you just added so that it will be simpler for you to reproduce.

**Comment by marco-m** [comment]
Ok I found the final problem: I was adding the voom plugin to the project.clj (as I wrote in the previous posts). If the plugin is there, then the failure is still there:

```
$ lein voom build-deps
-- build-deps for foo
Did not find, will build  {:groupId ring, :artifactId ring-core, :version 1.6.3-20171031_200203-gf7b8148}
[...]
'voom' is not a task. See 'lein help'.

Did you mean this?
         pom
Failed to resolve dependency: lein voom install error
{:exception-data
 {:exit 1,
  :cmd
  ["lein"
   "voom"
   "wrap"
   ":insanely-allow-dirty-working-copy"
   ":expected-version--1.6.3-20171031_200203-gf7b8148"
   "install"]}}
```

This is made worse by the fact that the return status of the command is 0, so an automatic test cannot detect the failure:

```
$ echo $?
0
```

On the other hand, if I put the voom plugin in `$USER/.lein/profiles.clj`, then the bug disappears.

Is the above behavior as expected or do you want me to write a PR adding the failing test ? (due to the 0 exit status, I will have to find a way around it)
